force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/ShopID__c.field-meta.xml
<CustomField>
    <fullName>ShopID__c</fullName>
    <description>Custom field_Picklist</description>
    <label>ShopID</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shop A</fullName>
            </value>
            <value>
                <fullName>Shop B</fullName>
            </value>
            <value>
                <fullName>Shop C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/renderclass.cls
Public class renderclass{

public string name{get;set;}
public string pcklst{get;set;}
public boolean checkbox{get;set;}
public shop__c shop{get;set;}
Public List<shop__c> shplst{get;set;}

public renderclass(){
shop=new shop__c();
checkbox=False;
name='Raushan';
}

public pagereference action(){

if(checkbox==true){
shplst=[select id,name,shopid__c from shop__c where name=:name and shopid__c=:shop.shopid__c];
}
else{
shplst=[select id,name,shopid__c from shop__c where name=:name];
}
return null;
}
}