force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/ShopID__c.field-meta.xml
<CustomField>
    <fullName>ShopID__c</fullName>
    <description>Custom field_Picklist</description>
    <label>ShopID</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shop A</fullName>
            </value>
            <value>
                <fullName>Shop B</fullName>
            </value>
            <value>
                <fullName>Shop C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/search.cls
public class search {
   public string searchval{get;set;}
   public shop__c shop{get;set;}
   Public Boolean checkbox{get;set;}
   public list<shop__c> shoplst{get;set;}
   
   public search(){
   shop=New shop__c();
   }
    public list<shop__c> getshoplst() {

        return shoplst;
    }
    Public Pagereference startsearch(){
    if(checkbox==True){
    shoplst=[select id,name,shopid__c from Shop__c where Name=:searchval and shopid__c=:shop.shopid__c];
    }
    else{
    shoplst=[select id,Name,shopid__c  from Shop__c where Name=:searchval];
    }
    return null;
    }

}